import { lazy, Suspense, useState } from 'react';
import { ArrowUpRight, Bot, Check, CreditCard, Dumbbell, Layers, ListChecks, TrendingUp, CalendarDays, MapPin } from 'lucide-react';
import type { ModuleProps, Page } from '../lib/types';
import { today } from '../lib/format';
import { dueSubscriptions, reminderLabel, weekday } from '../lib/lifestyle';
import { saveItem } from '../lib/api';
import { periodRangeLabel } from '../lib/course-times';
const SpatialMark=lazy(()=>import('../components/SpatialMark'));
export default function EraHome({data,refresh,notify,navigate}:ModuleProps&{navigate:(page:Page)=>void}){
  const date=today(data.profile.timeZone),trained=data.workouts.some(item=>item.date===date),due=dueSubscriptions(data.subscriptions,date),tasks=data.checklists.filter(item=>!item.dueDate||item.dueDate<=date).sort((a,b)=>Number(a.done)-Number(b.done)||a.dueDate.localeCompare(b.dueDate)).slice(0,5),[pending,setPending]=useState(new Set<string>());
  const workouts=data.workouts.filter(item=>item.date.startsWith(date.slice(0,7))),courses=data.courses.filter(item=>item.weekday===weekday(date)).sort((a,b)=>a.startPeriod-b.startPeriod);
  const hubs=[{page:'checklists' as Page,title:'每日计划',label:'完成一件，划掉一件',icon:ListChecks,color:'blue'},{page:'fitness' as Page,title:'薄肌日历',label:trained?'今天已经打卡':'简单运动，每日打卡',icon:Dumbbell,color:'green'},{page:'stocks' as Page,title:'每日股票',label:'台股优先，四个市场',icon:TrendingUp,color:'orange'}];
  async function toggle(item:typeof data.checklists[number]){if(pending.has(item.id))return;setPending(v=>new Set(v).add(item.id));try{await saveItem('checklists',{...item,done:!item.done},item.id);await refresh();notify(item.done?'已恢复计划':'已完成，计划已划掉');}catch(cause){notify((cause as Error).message);}finally{setPending(v=>{const next=new Set(v);next.delete(item.id);return next;});}}
  return <div className="page-stack era-home"><header className="era-greeting"><div><p>{new Intl.DateTimeFormat('zh-CN',{timeZone:data.profile.timeZone,month:'long',day:'numeric',weekday:'long'}).format(new Date())}</p><h1>{data.profile.name||'你'}，今天好。</h1></div><span className="greeting-badge">新的一天</span></header><section className="era-hero"><div className="era-hero-copy"><span className="hero-label">新时代版本答案</span><h2>AI + 薄肌 + 炒股</h2><p>让效率、状态和选择，<br/>都在自己的节奏里。</p></div><Suspense fallback={<div className="hero-mark"/>}><SpatialMark hero/></Suspense><div className="hero-pill-row"><span><Bot size={14}/>效率</span><span><Dumbbell size={14}/>状态</span><span><TrendingUp size={14}/>观察</span></div></section>
  <div className="hub-grid">{hubs.map(({page,title,label,icon:Icon,color})=><button className={`hub-card hub-${color}`} key={page} onClick={()=>navigate(page)}><span className="hub-icon"><Icon size={23}/></span><ArrowUpRight size={15}/><strong>{title}</strong><small>{label}</small></button>)}</div>
  <section className="panel home-plans"><div className="panel-header"><h2>今天的计划</h2><button className="text-button" onClick={()=>navigate('checklists')}>全部计划</button></div>{tasks.length?tasks.map(item=><button className={`mini-task ${item.done?'done':''}`} role="checkbox" aria-checked={item.done} aria-label={`${item.done?'取消完成':'完成'}：${item.title}`} disabled={pending.has(item.id)} key={item.id} onClick={()=>toggle(item)}><span className="task-check">{item.done&&<Check size={14}/>}</span><span>{item.title}</span>{item.dueDate&&<small>{item.dueDate<date?'逾期':item.dueDate}</small>}</button>):<div className="quiet-state"><ListChecks size={25}/><p>重要的事，先写进计划。</p><button className="text-button" onClick={()=>navigate('checklists')}>添加计划</button></div>}</section>
  <section className="panel home-courses"><div className="panel-header"><h2>今天的课表</h2><button className="text-button" onClick={()=>navigate('courses')}>一周课表</button></div>{courses.length?courses.map(item=><button className="home-agenda-row" key={item.id} onClick={()=>navigate('courses')}><span className="agenda-period">{periodRangeLabel(item.startPeriod,item.endPeriod)}</span><span><strong>{item.name}</strong><small>{item.room||'未填写教室'}</small></span><ArrowUpRight size={16}/></button>):<div className="quiet-state"><CalendarDays size={25}/><p>{data.courses.length?'今天没有课程，好好安排自己的时间。':'把课程和时间，放进自己的课表。'}</p><button className="text-button" onClick={()=>navigate('courses')}>查看课表</button></div>}</section>
  <div className="home-two-panels"><section className="panel today-status"><div className="panel-header"><h2>今天，照顾好自己</h2><Dumbbell size={20}/></div><div className="home-training-state"><div className={`mini-fitness-ring ${trained?'complete':''}`}>{trained?<Check size={25}/>:<Dumbbell size={25}/>}</div><div><strong>{trained?'运动已完成':'今天还未打卡'}</strong><p>本月已坚持 {workouts.length} 天</p></div></div><button className="button secondary" onClick={()=>navigate('fitness')}>{trained?'查看运动日历':'去运动打卡'}<ArrowUpRight size={15}/></button></section><section className="panel renewal-preview"><div className="panel-header"><h2>续费提醒</h2><span className="notification-count">{due.length}</span></div>{due.length?due.slice(0,3).map(item=><button key={item.id} className="renewal-mini" onClick={()=>navigate('subscriptions')}><span className={`service-icon category-${item.category}`}>{item.name.slice(0,1)}</span><div><strong>{item.name}</strong><small>{reminderLabel(item,date)}</small></div><Layers size={15}/></button>):<div className="quiet-state"><Check size={24}/><p>近期没有需要提醒的续费</p></div>}<button className="text-button" onClick={()=>navigate('subscriptions')}>管理订阅卡包 <ArrowUpRight size={14}/></button></section></div>
  <div className="utility-links"><button onClick={()=>navigate('documents')}><CreditCard size={22}/><div><strong>我的卡包</strong><small>{data.documents.length} 张证件，收在一处</small></div><ArrowUpRight size={17}/></button><button onClick={()=>navigate('subscriptions')}><Layers size={22}/><div><strong>订阅管理</strong><small>{data.subscriptions.filter(item=>item.active).length} 项正在使用</small></div><ArrowUpRight size={17}/></button><button onClick={()=>navigate('courses')}><CalendarDays size={22}/><div><strong>我的课表</strong><small>{data.courses.length} 门课，安排好每一天</small></div><ArrowUpRight size={17}/></button><button onClick={()=>navigate('places')}><MapPin size={22}/><div><strong>地图打卡</strong><small>{data.places.filter(item=>item.visited).length} 处足迹，还有更多想去</small></div><ArrowUpRight size={17}/></button></div><p className="era-home-footer">把每天过成自己的版本。</p></div>;
}
