import { useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Dumbbell } from 'lucide-react';
import { deleteItem, saveItem } from '../lib/api';
import { today } from '../lib/format';
import { monthDays, weekday } from '../lib/lifestyle';
import type { ModuleProps } from '../lib/types';
import { Field, PageHeading } from '../components/ui';
const days=['一','二','三','四','五','六','日'];
export default function Fitness({data,refresh,notify}:ModuleProps){
  const current=today(data.profile.timeZone),[month,setMonth]=useState(current.slice(0,7)),[selected,setSelected]=useState(current),[busy,setBusy]=useState(false),[error,setError]=useState(''),[minutes,setMinutes]=useState(20),[note,setNote]=useState('');
  const done=data.workouts.find(item=>item.date===selected),completedDays=new Set(data.workouts.map(item=>item.date)),completed=data.workouts.filter(item=>item.date.startsWith(month)),count=monthDays(month),blanks=weekday(`${month}-01`)-1;
  function choose(date:string){setSelected(date);setNote('');setMinutes(20);setError('');}
  function shift(amount:number){const [year,m]=month.split('-').map(Number),date=new Date(Date.UTC(year,m-1+amount,1));if(date.getUTCFullYear()<2000||date.getUTCFullYear()>2100)return;const next=date.toISOString().slice(0,7);setMonth(next);choose(next===current.slice(0,7)?current:`${next}-01`);}
  async function checkin(){if(busy)return;setBusy(true);setError('');try{if(done){await deleteItem('workouts',done.id);notify('已取消这天的打卡');}else{await saveItem('workouts',{date:selected,minutes,note});notify('训练完成，已打卡');}await refresh();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
  return <div className="page-stack fitness-page"><PageHeading title="薄肌日历" /><section className="fitness-month-card"><div className="fitness-month-top"><div><small>本月坚持</small><strong>{completed.length}<span>天</span></strong></div><div className="fitness-ring" style={{'--progress':`${completed.length/count*100}%`} as React.CSSProperties}><Dumbbell size={30}/></div><div><small>累计训练</small><strong>{completed.reduce((sum,item)=>sum+item.minutes,0)}<span>分钟</span></strong></div></div><p>{completed.length?'本月打卡记录':'本月尚未打卡'}</p></section>
  <section className="panel training-calendar"><div className="calendar-month"><button className="icon-button" aria-label="上个月" onClick={()=>shift(-1)}><ChevronLeft size={22}/></button><h2>{Number(month.slice(0,4))} 年 {Number(month.slice(-2))} 月</h2><button className="icon-button" aria-label="下个月" onClick={()=>shift(1)}><ChevronRight size={22}/></button></div><div className="calendar-weekdays">{days.map(day=><span key={day}>{day}</span>)}</div><div className="calendar-days">{Array.from({length:blanks},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:count},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,trained=completedDays.has(date);return <button key={date} aria-label={`${date}${trained?' 已打卡':''}`} aria-pressed={selected===date} className={`${trained?'trained':''} ${selected===date?'selected':''} ${date===current?'today':''}`} onClick={()=>choose(date)}><span>{i+1}</span>{trained?<Check size={11}/>:<span className="no-dot"/>}</button>;})}</div><div className="calendar-legend"><span><i className="green"/>已打卡</span><button className="text-button" onClick={()=>{setMonth(current.slice(0,7));choose(current);}}>回到今天</button></div></section>
  <section className={`panel day-training ${done?'day-complete':''}`}><div className="panel-header"><h2>{selected===current?'今天':`${Number(selected.slice(5,7))} 月 ${Number(selected.slice(-2))} 日`}的运动</h2><span className="pill">{done?`${done.minutes} 分钟 · 已打卡`:'等待打卡'}</span></div>{done?<div className="day-plan"><strong>训练已完成</strong>{done.note&&<p>{done.note}</p>}</div>:selected<=current?<><p className="muted small fitness-simple-note">运动完成后，记下今天的时长就好。</p><div className="two-fields"><Field label="训练分钟"><input type="number" min={1} max={240} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></Field><Field label="今天的感受（选填）"><input maxLength={300} value={note} onChange={e=>setNote(e.target.value)} placeholder="状态不错"/></Field></div></>:<p className="muted small">到了这一天，再记录你的运动。</p>}<button className={`button checkin-button ${done?'checked':''}`} disabled={busy||selected>current||(!done&&(!Number.isInteger(minutes)||minutes<1||minutes>240))} onClick={checkin}><Check size={20}/>{busy?'保存中…':selected>current?'这天还没到':done?'已打卡 · 点击取消':'完成训练，打卡'}</button>{error&&<p className="error-message" role="alert">{error}</p>}</section></div>;
}
