import { Printer, ArrowLeft, MapPin, Wallet, CalendarCheck, CircleCheck } from 'lucide-react';
import type { AppData, Page } from '../lib/types';
import { money, shortDate } from '../lib/format';
import { PageHeading } from '../components/ui';
export default function Report({ data, navigate }: { data: AppData; navigate: (p: Page) => void }) {
  const p = data.profile;
  const expenses = data.expenses.filter(e => (!p.semesterStart || e.date >= p.semesterStart) && (!p.semesterEnd || e.date <= p.semesterEnd));
  const total = expenses.reduce((sum, e) => sum + e.baseAmount, 0);
  const days = new Set(expenses.map(e => e.date)).size;
  const places = data.places.filter(p => p.visited);
  const allGroups = Object.entries(expenses.reduce<Record<string, number>>((a, e) => { a[e.category] = (a[e.category] || 0) + e.baseAmount; return a; }, {})).sort((a, b) => b[1] - a[1]);
  const groups: [string, number][] = allGroups.length > 7 ? [...allGroups.slice(0, 6), ['其餘分類', allGroups.slice(6).reduce((sum, entry) => sum + entry[1], 0)]] : allGroups;
  return <div className="page-stack report-page"><div className="spread no-print"><button className="text-button" onClick={() => navigate('settings')}><ArrowLeft size={16} />返回設定</button><button className="button" onClick={() => window.print()}><Printer size={17} />列印 / 儲存 PDF</button></div><article className="report-sheet"><div className="report-brand">Exchange life.<span>我的交換總結</span></div><PageHeading title={p.destination ? `在${p.destination}的日子` : '這一段，屬於我的旅程'} description={[p.name, p.school].filter(Boolean).join(' · ') || '從第一天，到難忘的每一天。'} /><p className="muted report-dates">{shortDate(p.departureDate)} — {shortDate(p.returnDate)}</p><div className="report-total"><Wallet size={24} /><span>學期總支出</span><strong>{money(total, p.baseCurrency)}</strong></div><div className="report-stats"><div><CalendarCheck size={22} /><strong>{days}<small>天</small></strong><span>認真記下生活</span></div><div><MapPin size={22} /><strong>{places.length}<small>個</small></strong><span>走過的新地方</span></div><div><CircleCheck size={22} /><strong>{data.checklists.filter(t => t.done).length}<small>件</small></strong><span>完成的小事</span></div></div><section className="report-categories"><h2>錢花在哪裡，也是一種生活記錄</h2>{groups.length ? groups.map(([category, value]) => <div className="report-category" key={category}><div className="spread"><span>{category}</span><span>{money(value, p.baseCurrency)} <small className="muted">{Math.round(total ? value / total * 100 : 0)}%</small></span></div><div className="progress-track"><div style={{ width: `${total ? value / total * 100 : 0}%` }} /></div></div>) : <p className="muted">還沒有支出記錄。從第一筆開始，慢慢累積你的故事。</p>}</section><section className="report-places"><h2>那些我去過的地方</h2><p className="muted">{places.length ? places.slice(0, 8).map(p => p.name.length > 25 ? p.name.slice(0, 25) + '…' : p.name).join('、') + (places.length > 8 ? `，還有 ${places.length - 8} 個地方` : '') : '地圖還是空白的，新的足跡正在路上。'}</p></section><footer className="report-footer"><span>生活在別處，回憶留在這裡。</span><span>Exchange life.</span></footer></article></div>;
}
