import { useState, type FormEvent } from 'react';
import { Download, LogOut, Smartphone, Check, CalendarPlus } from 'lucide-react';
import type { ModuleProps, Page, Profile } from '../lib/types';
import { api } from '../lib/api';
import { currencies, today } from '../lib/format';
import { downloadCalendar } from '../lib/lifestyle';
import { PageHeading, Field, SubmitButton } from '../components/ui';
export default function Settings({data,refresh,notify,logout,accountEmail}:ModuleProps&{navigate:(page:Page)=>void;logout:()=>void;accountEmail?:string}){
  const [form,setForm]=useState<Profile>({...data.profile}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[exporting,setExporting]=useState(false);
  const set=(key:keyof Profile,value:string)=>setForm(f=>({...f,[key]:value}));
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api('/profile',{method:'PUT',body:JSON.stringify(form)});await refresh();notify('设置已保存');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function exportData(){setExporting(true);setError('');try{const value=await api('/export'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`new-era-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);notify('全部资料与证件原件已导出');}catch(e){setError((e as Error).message);}finally{setExporting(false);}}
  return <div className="page-stack"><PageHeading title="设置" />{accountEmail&&<section className="panel"><div className="panel-header"><h2>我的账号</h2><span className="pill">已登录</span></div><p style={{overflowWrap:'anywhere'}}>{accountEmail}</p><p className="muted small" style={{marginTop:8}}>计划、卡包和打卡记录仅向你的账号开放。</p></section>}<form onSubmit={save} className="settings-form"><section className="panel"><div className="panel-header"><h2>个人偏好</h2></div><div className="form-grid"><Field label="怎么称呼你"><input value={form.name} onChange={e=>set('name',e.target.value)} maxLength={80} placeholder="你的名字" autoComplete="given-name"/></Field><Field label="日历与打卡时区"><select value={form.timeZone} onChange={e=>set('timeZone',e.target.value)}>{['Asia/Taipei','Asia/Shanghai','Asia/Hong_Kong','Asia/Tokyo','Asia/Seoul','Asia/Singapore','Asia/Bangkok','Europe/London','Europe/Paris','Europe/Berlin','Europe/Amsterdam','Europe/Stockholm','Europe/Zurich','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Toronto','America/Vancouver','Australia/Sydney','Pacific/Auckland'].map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></Field><Field label="记账本位币"><select disabled={data.expenses.length>0} value={form.baseCurrency} onChange={e=>set('baseCurrency',e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="常用外币"><select value={form.localCurrency} onChange={e=>set('localCurrency',e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></Field></div>{error&&<p className="error-message" role="alert">{error}</p>}<div className="form-actions"><SubmitButton busy={busy}><Check size={17}/>保存设置</SubmitButton></div></section></form><section className="panel"><div className="panel-header"><h2>资料与提醒</h2></div><button className="settings-action" onClick={exportData} disabled={exporting}><Download size={22}/><span><strong>{exporting?'整理中…':'导出全部资料'}</strong><small>含计划、订阅、打卡、卡包和此前保存的资料</small></span></button><button className="settings-action" disabled={!data.subscriptions.some(item=>item.active)} onClick={()=>downloadCalendar(data.subscriptions)}><CalendarPlus size={22}/><span><strong>导出 iPhone 日历提醒</strong><small>重复续费日程，含提前提醒</small></span></button></section><section className="panel install-panel"><Smartphone size={26}/><div><h2>加入 iPhone 主屏幕</h2><p>Safari 中点「分享」，选择「添加到主屏幕」。</p></div></section><div className="spread settings-footer"><span className="muted small">新时代版本答案 · 2.0</span><button className="button secondary" onClick={logout}><LogOut size={16}/>退出登录</button></div></div>;
}
