import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowUpRight, Plus, RefreshCw, Star, TrendingUp, Trash2 } from 'lucide-react';
import type { ModuleProps, StockMarket, StockQuote, WatchStock } from '../lib/types';
import { api, deleteItem, saveItem } from '../lib/api';
import { EmptyState, Field, Modal, PageHeading, SubmitButton } from '../components/ui';
const markets: { id: StockMarket; label: string; currency: string; hint: string }[] = [{id:'TW',label:'台股',currency:'TWD',hint:'2330、0050；上柜请填 6488.TWO'},{id:'US',label:'美股',currency:'USD',hint:'AAPL、NVDA、MSFT'},{id:'HK',label:'港股',currency:'HKD',hint:'0700、9988、3690'},{id:'CN',label:'A 股',currency:'CNY',hint:'600519、000001.SZ、300750'}];
const samples: Record<StockMarket, {symbol:string;name:string}[]> = {TW:[{symbol:'2330',name:'台积电'},{symbol:'0050',name:'元大台湾 50'},{symbol:'2317',name:'鸿海'}],US:[{symbol:'AAPL',name:'Apple'},{symbol:'NVDA',name:'NVIDIA'},{symbol:'MSFT',name:'Microsoft'}],HK:[{symbol:'0700',name:'腾讯控股'},{symbol:'9988',name:'阿里巴巴'},{symbol:'3690',name:'美团'}],CN:[{symbol:'600519',name:'贵州茅台'},{symbol:'000001.SZ',name:'平安银行'},{symbol:'300750',name:'宁德时代'}]};
export function Sparkline({ values, positive, large=false }: { values:number[]; positive:boolean; large?:boolean }) {
  if(values.length<2)return <p className="muted small">暂无足够的走势数据</p>;
  const min=Math.min(...values),max=Math.max(...values),height=large?120:32,width=large?320:85;
  const points=values.map((value,index)=>`${index/(values.length-1)*width},${height-6-(value-min)/Math.max(max-min,.01)*(height-12)}`).join(' ');
  return <svg className={`stock-sparkline ${positive?'positive':'negative'}`} viewBox={`0 0 ${width} ${height}`} role="img" aria-label="最近一个月每日价格走势" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="currentColor" strokeWidth={large?2.8:2} vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
export default function Stocks({ data,refresh,notify }:ModuleProps){
  const [market,setMarket]=useState<StockMarket>('TW'),[revision,setRevision]=useState(0),[selected,setSelected]=useState('2330');
  const [quotes,setQuotes]=useState<Record<string,StockQuote>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [draft,setDraft]=useState({symbol:'',name:''});
  const saved=data.watchlist.filter(item=>item.market===market),entries=useMemo(()=>saved.length?saved.slice(0,20):samples[market].map(item=>({...item,market,id:`sample-${market}-${item.symbol}`})),[data.watchlist,market]);
  const entryKey=entries.map(item=>item.symbol).join('|'),active=entries.find(item=>item.symbol===selected)||entries[0],quote=active?quotes[`${market}:${active.symbol}`]:null;
  useEffect(()=>{const control=new AbortController();setLoading(true);setErrors({});Promise.all(entries.map(async item=>{const key=`${market}:${item.symbol}`;try{const result=await api<StockQuote>(`/stocks/quote?market=${market}&symbol=${encodeURIComponent(item.symbol)}`,{signal:control.signal});if(!control.signal.aborted)setQuotes(value=>({...value,[key]:result}));}catch(cause){if(!control.signal.aborted){setErrors(value=>({...value,[key]:(cause as Error).message}));setQuotes(value=>value[key]?{...value,[key]:{...value[key],stale:true}}:value);}}})).finally(()=>{if(!control.signal.aborted)setLoading(false);});return()=>control.abort();},[market,entryKey,revision]);
  useEffect(()=>{const update=()=>{if(!document.hidden&&navigator.onLine)setRevision(value=>value+1);};const timer=setInterval(update,300000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);
  async function add(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{if(data.watchlist.some(item=>item.market===market&&item.symbol.toUpperCase()===draft.symbol.trim().toUpperCase()))throw new Error('这只股票已经在自选中');await saveItem('watchlist',{...draft,market});await refresh();setSelected(draft.symbol.trim().toUpperCase());setModal(false);notify('已加入自选');}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
  async function star(item:WatchStock){if(busy)return;setBusy(true);try{await saveItem('watchlist',{market:item.market,symbol:item.symbol,name:item.name});await refresh();setSelected(item.symbol);notify('已加入自选');}catch(cause){notify((cause as Error).message);}finally{setBusy(false);}}
  const format=(value:number)=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2,minimumFractionDigits:2}).format(value);
  return <div className="page-stack stocks-page"><PageHeading title="每日股票"  action={<button className="button" onClick={()=>{setDraft({symbol:'',name:''});setError('');setModal(true);}}><Plus size={17}/>自选</button>}/>
    <div className="market-tabs" role="group" aria-label="股票市场">{markets.map(item=><button key={item.id} aria-pressed={market===item.id} onClick={()=>{setMarket(item.id);setSelected(samples[item.id][0].symbol);}}>{item.label}</button>)}</div>
    <section className="panel market-feature"><div className="panel-header"><div><span className="market-code">{active?.symbol} · {markets.find(item=>item.id===market)?.currency}</span><h2>{active?.name||quote?.name||active?.symbol}</h2></div><button className="icon-button" aria-label="刷新行情" disabled={loading} onClick={()=>setRevision(value=>value+1)}><RefreshCw size={18} className={loading?'spin':''}/></button></div>{quote?<><div className="stock-large-price">{format(quote.price)}<span className={(quote.change||0)>=0?'stock-positive':'stock-negative'}>{quote.changePercent===null?'暂无涨跌幅':`${quote.changePercent>=0?'+':''}${quote.changePercent.toFixed(2)}%`}</span></div><Sparkline values={quote.history.map(row=>row.close)} positive={(quote.change||0)>=0} large/><div className="chart-dates"><span>{quote.history[0]?.date}</span><span>{quote.history.at(-1)?.date}</span></div><p className="quote-timestamp">行情时间 {new Intl.DateTimeFormat('zh-TW',{timeZone:data.profile.timeZone,dateStyle:'short',timeStyle:'short'}).format(new Date(quote.marketTime))}{quote.stale?' · 缓存行情':''}</p><a className="source-link" href={quote.sourceUrl} target="_blank" rel="noopener noreferrer">{quote.source} 原始行情 <ArrowUpRight size={13}/></a></>:<div className="quote-empty"><TrendingUp size={32}/><p>{loading?'正在获取市场数据…':active?errors[`${market}:${active.symbol}`]||'暂时没有行情':'添加一只股票开始关注'}</p></div>}</section>
    <section className="panel stock-list"><div className="panel-header"><h2>{saved.length?'我的自选':'市场观察'}</h2><span className="muted small">{saved.length?`${saved.length} 只`:'可添加到自选'}</span></div>{entries.map(item=>{const q=quotes[`${market}:${item.symbol}`];return <div className={`stock-row ${active?.symbol===item.symbol?'selected':''}`} key={item.id}><button className="stock-row-main" onClick={()=>setSelected(item.symbol)}><span className="stock-symbol-badge">{item.symbol.slice(0,2)}</span><div><strong>{item.name||q?.name||item.symbol}</strong><small>{item.symbol}</small></div>{q?<><Sparkline values={q.history.map(row=>row.close)} positive={(q.change||0)>=0}/><div className="stock-row-numbers"><strong>{format(q.price)}</strong><small className={(q.change||0)>=0?'stock-positive':'stock-negative'}>{q.changePercent===null?'—':`${q.changePercent>=0?'+':''}${q.changePercent.toFixed(2)}%`}</small></div></>:<span className="muted small">{loading?'载入中':'暂无行情'}</span>}</button>{item.id.startsWith('sample-')?<button className="icon-button" aria-label={`关注${item.name}`} disabled={busy} onClick={()=>star(item)}><Star size={16}/></button>:<button className="icon-button danger" aria-label={`移除${item.name||item.symbol}`} onClick={async()=>{try{await deleteItem('watchlist',item.id);await refresh();notify('已移除自选');}catch(cause){notify((cause as Error).message);}}}><Trash2 size={15}/></button>}</div>;})}</section>
    <p className="market-note">显示数据源提供的最新价格与每日走势，可能延迟。休市时保留最近交易日数据；不会生成模拟行情。</p>
    {modal&&<Modal title={`添加${markets.find(item=>item.id===market)?.label}自选`} onClose={()=>{if(!busy)setModal(false);}}><form onSubmit={add} className="form-grid"><Field label="股票代码" hint={markets.find(item=>item.id===market)?.hint}><input required autoCapitalize="characters" maxLength={20} value={draft.symbol} onChange={e=>setDraft({...draft,symbol:e.target.value})}/></Field><Field label="名称（选填）"><input maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field>{error&&<p className="error-message" role="alert">{error}</p>}<div className="form-actions"><SubmitButton busy={busy}>加入自选</SubmitButton></div></form></Modal>}
  </div>;
}
