import AccountGate from './components/AccountGate';
import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, Bell, CalendarDays, MapPin, House, CreditCard, ListChecks, Dumbbell, TrendingUp, Layers, Settings2, LoaderCircle, Menu, WifiOff, RefreshCw, Check, CalendarPlus } from 'lucide-react';
import type { AppData, Page } from './lib/types';
import { api } from './lib/api';
import { today } from './lib/format';
import { downloadCalendar, dueSubscriptions, reminderLabel } from './lib/lifestyle';
import { Modal } from './components/ui';
import EraHome from './pages/EraHome';
import Settings from './pages/Settings';
const Documents=lazy(()=>import('./pages/Documents')), Checklists=lazy(()=>import('./pages/Checklists')), Fitness=lazy(()=>import('./pages/Fitness')), Stocks=lazy(()=>import('./pages/Stocks')), Subscriptions=lazy(()=>import('./pages/Subscriptions'));
const Courses=lazy(()=>import('./pages/Courses')),Places=lazy(()=>import('./pages/Places'));
const navigation=[{page:'home',icon:House,label:'今日总览'},{page:'fitness',icon:Dumbbell,label:'薄肌日历'},{page:'stocks',icon:TrendingUp,label:'每日股票'},{page:'documents',icon:CreditCard,label:'我的卡包'},{page:'subscriptions',icon:Layers,label:'订阅卡包'},{page:'checklists',icon:ListChecks,label:'每日计划'},{page:'courses',icon:CalendarDays,label:'课表'},{page:'places',icon:MapPin,label:'地图打卡'}] as const;
function Brand(){return <span className="brand"><span className="brand-mark"><ArrowRight size={23}/><i/></span><span>新时代版本答案<small>AI · 薄肌 · 炒股</small></span></span>;}
export default function App(){
  const [status,setStatus]=useState<{authenticated:boolean;configured:boolean;user?:{email:string;name:string}|null}|null>(null),[data,setData]=useState<AppData|null>(null),[error,setError]=useState('');
  const [page,setPage]=useState<Page>('home'),[more,setMore]=useState(false),[notifications,setNotifications]=useState(false),[toast,setToast]=useState(''),[online,setOnline]=useState(navigator.onLine),[syncing,setSyncing]=useState(false);
  const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const refresh=useCallback(async()=>{setData(await api<AppData>('/data'));setError('');},[]);
  const boot=useCallback(async()=>{setError('');try{const next=await api<{authenticated:boolean;configured:boolean;user?:{email:string;name:string}|null}>('/auth/status');setStatus(next);if(next.authenticated)await refresh();else setData(null);}catch(e){setError((e as Error).message);}},[refresh]);
  useEffect(()=>{void boot();const expired=()=>{setStatus(s=>s?{...s,authenticated:false}:null);setData(null);setMore(false);setNotifications(false);};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired);},[boot]);
  useEffect(()=>{const change=()=>setOnline(navigator.onLine);window.addEventListener('online',change);window.addEventListener('offline',change);return()=>{window.removeEventListener('online',change);window.removeEventListener('offline',change);};},[]);
  useEffect(()=>{if(!status?.authenticated)return;const poll=()=>{if(!document.hidden&&navigator.onLine)refresh().catch(()=>{});};const interval=setInterval(poll,30000);window.addEventListener('focus',poll);document.addEventListener('visibilitychange',poll);return()=>{clearInterval(interval);window.removeEventListener('focus',poll);document.removeEventListener('visibilitychange',poll);};},[status?.authenticated,refresh]);
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  const notify=useCallback((message:string)=>{setToast(message);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),4000);},[]);
  const navigate=(next:Page)=>{setPage(next);setMore(false);setNotifications(false);window.scrollTo({top:0});};
  async function logout(){try{await api('/auth/logout',{method:'POST'});setData(null);setStatus({authenticated:false,configured:true});setPage('home');}catch(e){notify((e as Error).message);}}
  if(!status||(status.authenticated&&!data))return <main className="connection-state"><Brand/>{error?<><WifiOff size={30}/><h1>暂时连不上</h1><p className="muted">{error}</p><button className="button" onClick={boot}>重连</button></>:<><LoaderCircle className="spin" size={26}/><p className="muted">打开中…</p></>}</main>;
  if(!status.authenticated||!data)return <AccountGate brand={<Brand/>} onLogin={boot}/>;
  const props={data,refresh,notify},due=dueSubscriptions(data.subscriptions,today(data.profile.timeZone));
  return <div className="app-layout"><a className="skip-link" href="#main-content">跳至主要内容</a><aside className="sidebar"><button className="brand-button" onClick={()=>navigate('home')} aria-label="回到总览"><Brand/></button><div className="sidebar-section-label">我的日常</div><nav aria-label="主要导航">{navigation.map(({page:target,icon:Icon,label})=><button key={target} className={`nav-item ${page===target?'active':''}`} onClick={()=>navigate(target)} aria-current={page===target?'page':undefined}><Icon size={19} strokeWidth={1.7}/>{label}{page===target&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><button className={`nav-item ${page==='settings'?'active':''}`} onClick={()=>navigate('settings')}><Settings2 size={19}/>设置</button><div className="sidebar-user"><span className="avatar">{data.profile.name.slice(0,1)||'我'}</span><div><strong>{data.profile.name||'我的空间'}</strong><small>每天，更新自己的版本</small></div></div></div></aside>
  <div className="workspace"><header className="topbar"><div className="topbar-brand"><Brand/></div><div className="breadcrumb">我的空间<span>/</span>{navigation.find(n=>n.page===page)?.label||'设置'}</div><div className="topbar-actions"><span className={`sync-status ${online?'':'offline'}`}><i/>{online?'已同步':'离线'}</span><button className="icon-button sync-button" aria-label="同步资料" disabled={syncing||!online} onClick={async()=>{setSyncing(true);try{await refresh();notify('已同步');}catch(e){notify((e as Error).message);}finally{setSyncing(false);}}}><RefreshCw size={16} className={syncing?'spin':''}/></button><button className="icon-button notification-button" aria-label={`续费通知，${due.length} 项需要关注`} onClick={()=>setNotifications(true)}><Bell size={20}/>{due.length>0&&<span>{due.length>99?'99+':due.length}</span>}</button><button className="topbar-avatar avatar" aria-label="设置" onClick={()=>navigate('settings')}>{data.profile.name.slice(0,1)||'我'}</button></div></header>{!online&&<div className="offline-banner"><WifiOff size={16}/>当前离线，联网后可同步。</div>}<main id="main-content" className="main-content"><Suspense fallback={<div className="page-loading"><LoaderCircle className="spin"/>打开中…</div>}>{page==='home'?<EraHome {...props} navigate={navigate}/>:page==='fitness'?<Fitness {...props}/>:page==='stocks'?<Stocks {...props}/>:page==='subscriptions'?<Subscriptions {...props}/>:page==='documents'?<Documents {...props}/>:page==='checklists'?<Checklists {...props}/>:page==='courses'?<Courses {...props}/>:page==='places'?<Places {...props}/>:<Settings key={data.profile.baseCurrency} {...props} navigate={navigate} logout={logout} accountEmail={status.user?.email}/>}</Suspense></main></div>
  <nav className="ios-tabbar" aria-label="底部导航">{[{page:'home',icon:House,label:'今日'},{page:'fitness',icon:Dumbbell,label:'薄肌'},{page:'stocks',icon:TrendingUp,label:'股票'},{page:'documents',icon:CreditCard,label:'卡包'}].map(({page:target,icon:Icon,label})=><button key={target} className={page===target?'active':''} aria-current={page===target?'page':undefined} onClick={()=>navigate(target as Page)}><Icon size={23} strokeWidth={page===target?2.2:1.7}/><span>{label}</span></button>)}<button onClick={()=>setMore(true)} className={['subscriptions','checklists','courses','places','settings'].includes(page)?'active':''}><Menu size={23}/><span>更多</span></button></nav>
  {more&&<Modal title="我的空间" onClose={()=>setMore(false)}><nav className="more-grid" aria-label="全部页面">{[...navigation,{page:'settings' as const,icon:Settings2,label:'设置'}].map(({page:target,icon:Icon,label})=><button key={target} className={page===target?'active':''} onClick={()=>navigate(target)}><Icon size={24}/><span>{label}</span></button>)}</nav></Modal>}
  {notifications&&<Modal title="续费通知" onClose={()=>setNotifications(false)}>{due.length?due.map(item=><button className="notification-row" key={item.id} onClick={()=>navigate('subscriptions')}><span className={`service-icon category-${item.category}`}>{item.name.slice(0,1)}</span><span><strong>{item.name}</strong><small>{reminderLabel(item,today(data.profile.timeZone))} · {item.nextRenewal}</small></span><ArrowRight size={17}/></button>):<div className="quiet-state"><Check size={28}/><p>近期没有需要提醒的续费。</p></div>}<p className="muted small notification-note">按每项订阅设置的提前天数提醒。打开网站时会更新。</p><div className="form-actions"><button className="button secondary" onClick={()=>navigate('subscriptions')}>管理订阅</button>{data.subscriptions.some(item=>item.active)&&<button className="button secondary" onClick={()=>downloadCalendar(data.subscriptions)}><CalendarPlus size={16}/>导出日历</button>}</div></Modal>}
  {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}</div>;
}
